### ISSUE TITLE
Add funcitonality to return all parameters when parameter_name is not given

### ISSUE THREAD

**Issue by lukas-phaf** [EURODEO/e-soh#18]
Please add labels for relevant API endpoints.

**Comment by fjugipe** [comment]
Returning all parameters with /area endpoint using a large polygon will lead to message being larger than the 4MB limit of gRPC. Any ideas how we should handle this?

**Comment by Teddy-1000** [comment]
> Returning all parameters with /area endpoint using a large polygon will lead to message being larger than the 4MB limit of gRPC. Any ideas how we should handle this?

This is configurable. In the client and server side as far as I know. But I do not know if it is advisable to do so. @jo-asplin-met-no @lukas-phaf  do you know?

**Comment by lukas-phaf** [comment]
One thing is to turn on compression, I think you need to do it on both server and client side. I think it makes sense for this internal transaction.

But that is only a temporary fix.

I would not recommend just changing the size, I don't think it is recommended to make gRPC messages very large.

There are two real solutions:
1. Use streaming gRPC, and chunk up the data. This means query can take very long, as all the data needs to be sent and transformed into JSON.
2. Do a rough estimate up front on how large the number of points is going to be (based on area x time range x number of return parameters), and limit this to a certain number of points. So small are with a large time range is okay, and large area with small time range as well, but not large area with large time range. This also helps to keep the response time of a query within limt.

In KNMI we do the second for our EDR API.

**Comment by lukas-phaf** [comment]
But practically speaking, I would make handling this a separate issue.
