### ISSUE TITLE
Regard only a subset of the TSMetadata fields as the time series key

### ISSUE THREAD

**Issue by jo-asplin-met-no** [EURODEO/e-soh#37]
It should be possible that only some of the fields in TSMetadata define a unique time series. This allows "non-key" fields of a given time series to be updated without having to create a completely new time series. Typical use cases include fixing typos and updating the contents of the _links_ field (list of alternative landing pages to the underlying time series etc.).

**Comment by jo-asplin-met-no** [comment]
Candidates for such a "unique combination" subset:

- naming_authority
- platform
- standard_name
- level
- function
- period
- instrument

All other fields may then be updated (i.e. **overwritten**!) by PutObservations calls made by the ingestor.

**Comment by jo-asplin-met-no** [comment]
Just a reality check: What's the rationale of keeping the metadata_id with each observation? I understand that it works like a reference to the time series to which the observation belongs. But wouldn't that be useful only in the case where it would be practical (or even required) to handle individual observations in isolation / out-of-context? And would that really be the case here? I mean, isn't it always the case that the time series in question - with all the ts-specific metadata - is readily available in all systems that process data from E-SOH? And why do we then need this reference explicitly in each obs? Couldn't we simply remove it? (may not an entirely transferable example, but it's hard to come up with a use case for keeping a ref to the image explicitly in every single pixel of a digital image)

**Comment by Teddy-1000** [comment]
For the metadata feature endpoint we need an ID of some kind to reference a single feature, in our case a time series. We are not shipping all metadata with the covjson data, so we need a simple way of looking up the time series. We do not need to explicitly keep the metadata_id with all observations though.

**Comment by jo-asplin-met-no** [comment]
Then I suggest to move metadata_id to TSMetadata since this is metadata that doesn't change between observations within the same time series. I.e. something like this:

> diff --git a/protobuf/datastore.proto b/protobuf/datastore.proto
> index a78771e..14d360b 100644
> --- a/protobuf/datastore.proto
> +++ b/protobuf/datastore.proto
> @@ -103,6 +103,7 @@ message TSMetadata {
>    string period = 25;
>    string function = 26;
>    string parameter_name = 27 [json_name = "parameter_name"];
> +  string metadata_id = 28 [json_name = "metadata_id"];
>    // --- END string metadata -----------------
>  }
> 
> @@ -123,7 +124,6 @@ message ObsMetadata {
>    string id = 6;
>    string data_id = 7 [json_name = "data_id"];
>    string history = 8;
> -  string metadata_id = 9 [json_name = "metadata_id"];
>    string processing_level = 10 [json_name = "processing_level"];
>    // --- END string metadata -----------------

Any objections? It does require a small (presumably trivial) change in both ingestor and api.

**Comment by lukas-phaf** [comment]
Would it be part of the "unique key" for the time series?

**Comment by jo-asplin-met-no** [comment]
No, but there is a 1-1 correspondence between metadata_id and the unique key. And that is in fact another argument for keeping metadata_id it in TSMetadata, since that's where the unique key fields are. So metadata_id is really just a convenient way to refer to the time series (= feature) as Amund pointed out. And I guess the reason it needs to be computed already by the ingestor is essentially that it is more convenient/robust for an MQTT event consumer to refer to a single metadata_id instead of the combination of 7 keys. If I had understood this correctly.

**Comment by lukas-phaf** [comment]
So the metadata_id could be calculated as the hash of the combination of the 7 keys?

**Comment by Teddy-1000** [comment]
> So the metadata_id could be calculated as the hash of the combination of the 7 keys?

Yes, that is the idea.
