### ISSUE TITLE
Have GetObservations return the latest observation(s) from each time series

### ISSUE THREAD

**Issue by jo-asplin-met-no** [EURODEO/e-soh#40]
It is useful to specify that you want only the latest observation(s) when calling the gRPC method GetObservations.

We propose to support this by introducing an "enum" field `temporal_mode` to GetObsRequest with the following meaning:

**Case 1**: `temporaral_mode` = "interval" ---> Specify the field `temporal_interval` to retrieve observations only inside this range from the otherwise matching time series. This is the default mode (which ensures backwards compatibility as this is the default behavior).

**Case 2**: `temporal_mode` = "latest" ---> By default retrieve the single latest observation from the otherwise matching time series. This mode could also recognize fields `latest_limit` (default: 1) and `latest_maxage` (default: entire valid time range, i.e. normally PT24H) to further control what observations to get.

**Comment by lukas-phaf** [comment]
Looks good. Do you think all these should be at the top level GetObsRequest (making it backwards compatible), or should there be a TemporalRange proto object that has all this info?

**Comment by jo-asplin-met-no** [comment]
I think that for simplicity, these should simply be added to GetObsRequest for now. We can always refactor into a multilevel structure later if we like (typically if many more fields of different categories are added to GetObsRequest). Breaking backwards compatibility isn't that much of concern anyway since this is an internal API.

**Comment by lukas-phaf** [comment]
Ok, sounds good.

**Comment by jo-asplin-met-no** [comment]
Closed with [this PR](https://github.com/EURODEO/e-soh/pull/41).
