### ISSUE TITLE
Add response_fields to GetObsRequest to limit size of GetObsResponse

### ISSUE THREAD

**Issue by jo-asplin-met-no** [EURODEO/e-soh#51]
It should be possible to limit the size of a `GetObsResponse` message dynamically so that only the fields specified in a new field `response_fields` in `GetObsRequest` are included.

This feature will be important to reduce the likelihood of calls to `GetObservations` failing due to gRPC message size limit being exceeded.

**Example:** At the time of writing there are around 17160 distinct time series in the test instance at MET Norway. Calling `GetObservations` to get even just the latest observation from each time series results in a `GetObsResponse` message of 11MB, which causes the call to fail since the limit is 4MB.

**Comment by lukas-phaf** [comment]
I switched the locations endpoint over to using this.

For the KNMI test data, the response size before this change was `341012`.
The response size after the change is `220314`.

The size change is limited, but the KNMI dataset really only has the fields filled in to make the API work. It took 98 ms.
