### ISSUE TITLE
[DATASTORE] Improve performance of `/items/{item_id}` query

### ISSUE THREAD

**Issue by lukas-phaf** [EURODEO/e-soh#72]
`/items/{item_id}` is now significantly slower than using the `/items` endpoint with a `bbox` or `platform` parameter.

This probably will be solved by moving the `metadata_id` to the timeseries metadata table, see #47. If not, look into adding an index for it.

**Comment by jo-asplin-met-no** [comment]
So _metadata_id_ is needed in ObsMetadata after all @lukas-phaf ? [I thought maybe it wasn't](https://github.com/EURODEO/e-soh/issues/47).

**Comment by jo-asplin-met-no** [comment]
@lukas-phaf: Fixed with this [PR](https://github.com/EURODEO/e-soh/pull/78) (`ObsMetadata.metadata_id` has been moved to `TSMetadata.timeseries_id`).

**Comment by lukas-phaf** [comment]
Yes, I tested it, and it is indeed fixed.
