### ISSUE TITLE
Add temporal filter and parameter-name to locations endpoint

### ISSUE THREAD

**Issue by Teddy-1000** [EURODEO/e-soh#95]
The `/locations` endpoint should make a temporal filter available.
The `/locations` should also have parameter-name filter.

**Comment by lukas-phaf** [comment]
What should this select on? Only give back stations that have data in this period? Is this useful if we only store 24 hours of data? It feels like it is very unlikely for a station to be there, but not to have data?

**Comment by Teddy-1000** [comment]
> What should this select on? Only give back stations that have data in this period? Is this useful if we only store 24 hours of data? It feels like it is very unlikely for a station to be there, but not to have data?

Maybe not often, but I think we should support it.

**Comment by fjugipe** [comment]
Do we want to add the temporal filter to properties section of each feature when filtering with it? E.g.:
```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
       ...,
       ...
    ]
  },
  "properties": {
    "name": "...",
    "detail": "...",
    "datetime": "2024-03-26T00:00:00Z/2024-03-26T06:00:00Z",
    "parameter-name": [...]
  },
  "id": "..."
}
```
What about the situations when there is no temporal filter, as Lukas stated we only have 24 hours of data?

**Comment by lukas-phaf** [comment]
> Maybe not often, but I think we should support it. There are some edge cases where it might be useful. For example if you would like to find all locations that have had updates the last 5 minutes. This also reduces the amount of data that need to be transmitted.

Fair enough. It should be trivial to implement anyway, just pass it to the datastore, right?

**Comment by lukas-phaf** [comment]
> Do we want to add the temporal filter to properties section of each feature when filtering with it? E.g.:

I am not a fan of doing this, as it implies there is only data for the requested period...

**Comment by fjugipe** [comment]
> > Do we want to add the temporal filter to properties section of each feature when filtering with it? E.g.:
> 
> I am not a fan of doing this, as it implies there is only data for the requested period...

I agree with this one and the user should already know the period because based on the request. I will leave it as is for now and we can do it later if really needed.
